### ISSUE TITLE
[QUESTION] - How many loop for DAY1-pt2 ?

### ISSUE THREAD

**Issue by ibbatta** [adriennetacke/advent-of-code-2018#1]
I run my script (very similar to yours) and it's looping many times but is a bit weird, how many loop did you do before found the duplicate frequence?

**Comment by adriennetacke** [comment]
I don't have an exact number, I actually have a while loop running until I find the duplicate.

What seems to be happening with your solution?

**Comment by ibbatta** [comment]
Actually I don't know...
This operation seems to be quite long! (that's why I would know how many loops ahahah)

![screenshot at 2018-12-05 18 57 33](https://user-images.githubusercontent.com/4375285/49533591-b2fa7300-f8bf-11e8-8e11-623b51cd5945.png)

**Comment by adriennetacke** [comment]
Hmm, at best guess, it looks like an infinite loop! Does it just freeze at the point in your screenshot?

**Comment by ibbatta** [comment]
Still running, It's only a screen, but it takes too long to process data
(but not an infinite loop, I've tested it with a smaller array)... that's
why I was curious to know ho many loop.

**Comment by ibbatta** [comment]
Ok solved doing  `for` loop instead  `forEach` (don't know why... I will spend next days studying why, sigh)

**Comment by adriennetacke** [comment]
I'm glad you resolved it somehow!
